### ISSUE TITLE
META: CKE5 integration

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#2002]
### How to test?

The default text editor is now configurable in Settings.yaml:

```
Neos:
  Neos:
    Ui:
      frontendConfiguration:
        defaultInlineEditor: 'ckeditor5'
```

### TODO:

- [x] wait for  removeformat to be implemented in https://github.com/ckeditor/ckeditor5/issues/908
- [x] test, make sure it's rock solid, then release a major version making CKE5 the default editor
- [ ] ctrl+k should open link editor

**Comment by DrillSergeant** [comment]
@dimaip , could you change the handling of link-schemes in CKE5 integration? In CKE4 the possible schemes are mentioned in Packages/Application/Neos.Neos.Ui/packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js in this construct:
```
const isUri = str =>
    str && Boolean(str.match('^(https?://|mailto:|tel:|#)'));
```
Sometimes (especially for intranet-projects) there are more url-schemes that should work (like "notes://" for lotus-notes documents). In CKE4 I cannot extend that because it's hardcoded and so it takes a lot of work to make linking to those schemed-links possible in RTE.
I would love if you could make this configurable via settings to add additional schemes so the CKE5-link editor accepts those custom schemes.
I just had a slack call with @kitsunet where he mentioned even some more ideas. Maybe you guys can talk/discuss. Remember, a simple solution for my usecase would help for many cases I think. I guess (hope) it's not so hard to check settings for some extra schemes.

**Comment by DrillSergeant** [comment]
@dimaip ah nice, thank you.

**Comment by danielkestler** [comment]
We can close this, can we?
