### ISSUE TITLE
Remove classes marked as deprecated and can be removed by 6.0

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2798]
### Description

We have a upcomming major release in some weeks and therefore we need to check which deprecations we need to remove.
Sadly in the ui we did not deprecate that much stuff and also did not tag it to versions.

So we have to check history when the marked deprecations has been added.

### TODOs

- [x] Remove the legacy aloha configuration handling (#2802)
- [x] Remove deprecated isDisabled Button prop (#2803)
- [x] Make the content UI a backend module with its own module privilege (#2793)
- [x] Remove legacy fusion code of the old emberjs content module (#2849)

**Comment by markusguenther** [comment]
@bwaidelich Guess it is too early to just support the  constraints.mediaTypes right. So it is more a thing for the 7.0 right?

**Comment by markusguenther** [comment]
The PR from @daniellienert also removes some deprecations :)
https://github.com/neos/neos-ui/pull/2793

**Comment by bwaidelich** [comment]
@markusguenther since the todos seem to be done, can this be closed?
