### ISSUE TITLE
EPIC: E2E Tests for Neos 9.0

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3546]
This issue covers everything related to E2E Tests on Neos 9.0. There have already been some issues open with regards to 9.0, but we need to fix some problems that exist in the 8.x-branches first.

## 8.x-related

- [x] https://github.com/neos/neos-ui/issues/3301
- [x] https://github.com/neos/neos-ui/issues/3540

## 9.0-related

- [x] https://github.com/neos/neos-ui/issues/3406
- [ ] https://github.com/neos/neos-ui/issues/3542
- [x] https://github.com/neos/neos-ui/issues/3541
