### ISSUE TITLE
Road to 1.0 -- 1.0 Must-Haves

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#687]
In this post, I am trying to sketch out the Road to Neos React UI 1.0.0, give estimates, and try to collect everything together.

## Definition: Must Have for 1.0.0

How do we decide whether a feature is must-have or not for 1.0.0? Especially for 1.0.0 releases, we often try to cram as much as possible in. That's why for the React UI, we apply the following guidelines.

**Issues are a must-have for 1.0.0, iff:**

* they are a core feature of the old UI and haven't been ported yet, especially in the area of inspectors & content editing.
* they are an issue appearing on many websites (e.g. if editing broke when applied on inline elements)
* they are a performance problem for larger websites

**Issues are NO must-have for 1.0.0, if:**

* they just appear anecdotically
* there exist workarounds which are understandable to the normal editor
* minor styling polishing

## Main Areas of Work

The following areas are the main areas where work is still needed.

Each point links to the respective issue; where a concept for the
corresponding component is explained:

* [ ] **P1??Unsure?** #647: Do not send full serialized node info for UI updates
* Inspector Editors
  * [x] #874 file upload editor
  * [x] #875 links to assets in Link Editor
  * [x] #876 assets editor
  * [x] **P1** #833 After changing inspector property, you are not forced to apply changes
  * [x] #1014 "Selected Element" is missing in Inspector
  * [x] #1037 "Change Type" in inspector doesn't handle auto-created child nodes correctly
* Node Tree
  * [x] #866: Content and Document tree should scroll when moving nodes through drag/drop
  * [ ] #867: Add extension point for overriding element Rendering in Node Trees
* API Requests
  * [x] **P1** #901 show re-login dialog if session timed out to ensure people do not loose content
  * [x] **P1** #841: Properly handle exceptions in API requests
* [ ] switch to context identifier from context path - see https://github.com/neos/neos-development-collection/pull/1614

### to validate / retest

*If you want to help, you can pick one of these bugs, try to reproduce it, and add some comments/screenshots.*

* [x] #596: breaks in the text of a headline NodeType do not show up after publishing

### Confirmed Bugs

These bugs don't carry big conceptual TODOs; they can just be solved.

*If you want to help, pick one of these bugs, and try to fix it.*

* Dimension Handling
  * [ ] #697: If more than one dimension - urls for preview and backend are wrong
  * [ ] #755:  Fatal Error in DimensionSwitcher on dimension with multiple values 

* Rich Text Editor
  * [ ] #829: Text aligning options
  * [ ] **P2** #834: Editables with span tagName behaves strangely when pasting content
  * [ ] #865: Allow to set extra styles on Span and Div elements

* General UI
  * [ ] #802: Tooltips for buttons
  * [ ] #1038: UI should scroll to newly inserted content element
  * [ ] #1015: Not-Inline-Editable overlay is missing
  * [ ] #1040: Dimension switcher should close after selection
  * [ ] #1042: PageTree is empty after switching to another dimension

## Done, Reviewed, Merged
* [x] #863: Make Background Color in ContentCanvas configurable 
* [x] #719: Wrong escaping for title in document tree
* [x] #749: Nodes in the page tree only show as hidden when they are selected
* [x] #688: "Edit / Preview" buttons slides as buttons are clicked
* [x] #577: Inspector Date Time Picker not saving
* [x] #652: Remove `<p></p>` in placeholders
* [x] #668: Editables with tagName other than `div` (e.g. span) cause an infinite loop in CKeditor (Difficult!)
* [x] #369: (ImageEditor) Persisted Aspect ratio is not accurately re-calculated in the Cropper
* [x] #370: (ImageEditor) Support locked aspect ratio
* [x] #691 references editor
  * [x] #683 links to external URLs
  * [x] unstable: reference editor
  * [x] editor data sources
* [x] node tree search
* [x] #632 (PR): Refactor Content initialization and move to separate package
* [x] **P1** #764 (PR) Improve SelectEditor / MultiSelectEditor
  * [x] #725 implement Data Sources in Select Editor
  * [x] #649  Make MultiSelectBox component searchable
* [x] #836: Can't select time in Datetime editor
* [x] #806: Mark a new change in the page/content tree
* [x] **P1** #645: Editing URL path segment is not supported
* [x] #609: Copy Pasting Content Collection should be disallowed is it's an auto created child
* [x] **P1** #837: Inspector tabs that only have views and no editors are hidden.
* [x] **P1** #826 When switching focused node, inspector becomes blank if the focused nodetype doesn't have that group
* [x] **P1** #842: Editing a property from another page causes browser tab to freeze and crash
* [x] **P1** #835: Scrolling contentCanvas is a bit weird
* [x] #862 node tree filter
* [x] #824: Cannot add element to a container child node element
* [x] #766: Pages can be added after main content collection
* [x] #831: Inline UI overrides styling of scrollbars inside contentcanvas 
* [x] #815: When the canvas is reloaded after applying inspector, it doesn't scroll back to reveal the focused node
* [x] #852: Cropping an image: Swtich aspect ratio does not work
* [x] #864: Make Dropdown menus (like workspace menu) scrollable if they contain lots of content
* [x] **P1** #791:  Discard a newly created document node leads to errors
* [x] **P1** #794:  Node still rendered in guest frame after deletion

## Meta: Issue Management Methodology

* The issue #687 is the main meta-issue tracking everything
  to the React Rewrite 1.0.0 release.
* Every issue which is on the *must-have* list for 1.0.0 must
  have a link back on top like **[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**
* All must-haves must be in the milestone *must-have for 1.0.0*
* We're using Draw.io for diagrams, using "File -> Export as -> URL" and linking the resulting URL.
  This embeds the full diagram source code into the URL, making it self-contained in the issue.

**Comment by dimaip** [comment]
Basically almost every part of UI needs more detailed work and testing. From styling, to behavior, keyboard navigation etc etc.
Content tree needs to be more synced to the canvas, e.g. scroll to focused node and scroll canvas the other way. Anyways, no need to get too detailed here, we have issues for it.

Also, you keep on adding target workspace selector. :) What's wrong with the current implementation?

**Comment by skurfuerst** [comment]
I'm closing this meta-issue, as 1.0.0 is released!
